coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  # para incluir archivos estáticos

urlpatterns = [
    path("", include("products.urls")),
    path("admin/", admin.site.urls),
    path("usuarios/", include("users.urls")),
    path("pedidos/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import MyOrderView
from .views import CreateOrderProductView

urlpatterns = [
    path("mi-orden/", MyOrderView.as_view(), name="my_order"),
    path("agregar-producto", CreateOrderProductView.as_view(), name="add_product"),
]

products/urls.py
from django.urls import path
from .views import ProductFormView, ProductListView, ProductListAPI

urlpatterns = [
    path("", ProductListView.as_view(), name="list_product"),
    path("api/", ProductListAPI.as_view(), name="list_product_api"),
    path("agregar/", ProductFormView.as_view(), name="add_product"),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView


urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registro/", RegisterView.as_view(), name="register"),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"order {self.id} by {self.user}"


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self):
        return f"order product {self.id} for {self.order} and {self.product}"

products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.TextField(max_length=100, verbose_name="Nombre")
    description = models.TextField(max_length=300, verbose_name="Descripción")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio")
    avilable = models.BooleanField(default=True, verbose_name="Disponible")
    photo = models.ImageField(
        upload_to="logos", null=True, blank=True, verbose_name="Foto"
    )
    date_created = models.DateField(
        auto_now_add=True, verbose_name="Fecha de creación", null=True
    )

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct


class OrderProductForm(ModelForm):
    class Meta:
        model = OrderProduct
        fields = ["product"]

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.Form):  # formulario
    name = forms.CharField(max_length=200, label="Nombre")
    description = forms.CharField(max_length=300, label="Descripción")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    avilable = forms.BooleanField(initial=True, label="Disponible", required=False)
    photo = forms.ImageField(label="Foto", required=False)
    date_created = forms.DateField(label="Fecha de creación", required=False)

    def save(self):  # metodo de guardar, por medio de un diccionario
        Product.objects.create(
            name=self.cleaned_data["name"],
            description=self.cleaned_data["description"],
            price=self.cleaned_data["price"],
            avilable=self.cleaned_data["avilable"],
            photo=self.cleaned_data["photo"],
            date_created=self.cleaned_data["date_created"],
        )

orders/views.py
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
)  # para que el usuario tenga que estar logeado
from django.urls import reverse_lazy
from .models import Order
from .forms import OrderProductForm

# Create your views here.


class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/my_order.html"
    context_object_name = "order"

    def get_object(self, queryset=None, *args, **kwargs):

        return Order.objects.filter(user=self.request.user, is_active=True).first()


class CreateOrderProductView(LoginRequiredMixin, CreateView):
    template_name = "orders/my_order.html"
    form_class = OrderProductForm
    success_url = reverse_lazy("my_order")

    def form_valid(self, form):
        order, _ = Order.objects.get_or_create(
            is_active=True,
            user=self.request.user,
        )
        form.instance.order = order
        form.instance.quantity = 1
        form.save()
        return super().form_valid(form)

products/views.py
from django.shortcuts import render
from django.views import generic
from rest_framework.response import Response
from rest_framework.views import APIView
from django.urls import reverse_lazy
from .forms import ProductForm
from .models import Product
from .serializers import ProductSerializer


class ProductFormView(generic.FormView):
    template_name = "products/add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy("list_product")

    def form_valid(self, form):  # guardas los datos en la base de datos
        form.save()
        return super().form_valid(form)


class ProductListView(generic.ListView):
    model = Product
    template_name = "products/list_product.html"
    context_object_name = "products"


class ProductListAPI(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)  # para importar en formato json

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("login")


# Create your views here.

orders/templates/orders/create_order_product.html
HOLA

orders/templates/orders/my_order.html
{% extends "base.html" %}

{% block content %}
<div class="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
    <h2 class="text-2xl font-bold mb-4">Detalles de la Orden</h2>
    <div class="mb-2">
        <span class="text-lg font-semibold">Usuario: </span>
        <span class="text-lg">{{ order.user.username|title }}</span>
    </div>
    <div class="mb-2">
        <span class="text-lg font-semibold">Fecha de la Orden: </span>
        <span class="text-lg">{{ order.order_date|date:"F j, Y H:m" }}</span>
    </div>

    <div class="mt-6">
        <h3 class="text-xl font-bold mb-2">Artículos en tu orden:</h3>
        {% for product_order in order.orderproduct_set.all %}
            <div class="flex justify-between items-center py-2 border-b">
                <div class="text-lg">{{ product_order.product.name }}</div>
                <div class="text-lg font-semibold">{{ product_order.product.price }}</div>
            </div>
        {% empty %}
            <div class="text-red-500">No hay artículos en tu orden</div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

products/templates/products/add_product.html
Aqui saldra el formulario


<form action="{% url "add_product" %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Agregar</button>


</form>

products/templates/products/list_product.html
{% extends "base.html" %}

{% block content %}
<div class="grid grid-cols-1 gap-4 md:grid-cols-4 md:gap-8 mt-8">
    {% for product in products %}
        <div class="h-32 rounded-lg bg-gray-200">
            <a href="#" class="group relative block overflow-hidden">
                <button
                class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
                >
                <span class="sr-only">Wishlist</span>
            
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="h-4 w-4"
                >
                    <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
                    />
                </svg>
                </button>
                {% if product.photo %}
                <img
                    src="{{ product.photo.url }}"
                    alt="{{ product.name }}"
                    class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
                />
                {% endif %}
                <div class="relative border border-gray-100 bg-white p-6">
                <span class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"> New </span>
            
                <h3 class="mt-4 text-lg font-medium text-gray-900">{{ product.name }}</h3>
            
                <p class="mt-1.5 text-sm text-gray-700">${{ product.price }}</p>
                    
                    <form action="{% url "add_product" %}" class="mt-4" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product" value="{{product.id}}">
                    <button
                        class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
                    >
                        Agregar al pedido
                    </button>
                    </form>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "base.html" %}   
{% load tailwind_filters %}

{% block content %}
<h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Iniciar sesión</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button 
    class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
    type="submit">Login
    </button>
</form>
{% endblock content %}

users/templates/users/logout.html
{% extends "base.html" %}   
{% load tailwind_filters %}

{% block content %} 
<h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Sesión finalizada</h1>
<p class="text-gray-700 text-lg">
¡Gracias por utilizar nuestra web! 
</p>

{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="container mx-auto w-1/3">
    <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Iniciar sesión</h1>
    <form action="" method="post" class="my-8">
        {% csrf_token %}
        {{ form|crispy }}
        <button
            class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500" 
            type="submit">
            Registrarse
        </button>
    </form>
    <p class="text-center text-sm text-gray-500 mt-4">
        Ya tienes una cuenta
        <a class="underline" href="{% url "login" %}">Inicia sesión</a>
    </p>
</div>
{% endblock content %}